name:                abletonlive-xml
version:             0.1.0.0
github:              "karamellpelle/abletonlive-xml"
license:             GPL-3
author:              "karamellpelle@hotmail.com"
maintainer:          "karamellpelle@hotmail.com"
copyright:           "2019 Carl Joachim Svenn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/karamellpelle/abletonlive-xml#readme>

# package versions will be relative to the choosen LTS (?)
dependencies:
- base >= 4.7 && < 5
- easy-file # TODO: use rio instead
- gitrev
#- transformers

library:
  source-dirs: lib-source
  dependencies:
  - zlib
  - bytestring
  - xml
  - rio

executables:
  abletonlive-xml:
    main:                Main.hs
    source-dirs:         app-source
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # taken from https://github.com/commercialhaskell/rio
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -Wno-unused-imports
    dependencies:
    - rio
    - optparse-simple
    - abletonlive-xml
    #default-extensions: # LANGUAGE pragmas; see https://github.com/commercialhaskell/rio#language-extensions
    default-extensions:
    - NoImplicitPrelude

    
#tests:
#  abletonlive-xml-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - abletonlive-xml
